### ISSUE TITLE
HSTS check returns a false-negative

### ISSUE THREAD

**Issue by thedufer** [RaymiiOrg/ssl-decoder#11]
Specifically, my response includes:

```
Strict-Transport-Security: max-age=31536000;
```

But the check says that I do not have the HSTS header set.

I think this is distinct from #10 because my casing matches that in the code, but I could be wrong.

**Comment by RaymiiOrg** [comment]
Please provide more information. Which host do you test?

**Comment by thedufer** [comment]
I'm seeing this on threegoodthings.xyz

The tester at https://www.ssllabs.com/ssltest/ correctly sees that I have the HSTS header set.

**Comment by RaymiiOrg** [comment]
curl on the command line on multiple test hosts doesn't show it:

    $ curl -I https://threegoodthings.xyz
    HTTP/1.1 404 Not Found
    Server: nginx/1.1.19  
    Date: Fri, 27 Mar 2015 19:14:34 GMT  
    Content-Type: text/html
    Connection: keep-alive

The chrome developer console does show it. Seems to be a server issue.

**Comment by thedufer** [comment]
Oh, I see why you're missing it.  That server doesn't respond properly to HEAD reqs, which should be irrelevant.  I mean, technically it should server the same headers as to a GET (not sure why nginx isn't doing the right thing here since it's in charge of that header), but the GET is the one that matters in practice.  You should be checking on a GET, I think.

**Comment by RaymiiOrg** [comment]
HEAD requests use much less data and thus are faster. Please fix server side.

**Comment by thedufer** [comment]
I would suggest a note in the README that this tool prefers saving bandwidth over false-negatives if that's what you're going to do.  Kinda weird to knowingly tell people something that's wrong.  I guess I'll go back to using ssltest, though, so I don't really care.

**Comment by fkooman** [comment]
Hi, this fix is still is not live it seems? I'm seeing the same false positive on indiecert.net, my server also doesn't respond correctly to HEAD requests, which is a bug, I agree, but it is not a TLS bug. So actually your service gives misinformation ;-) It should say: your GET/HEAD response headers do not match... :)

**Comment by RaymiiOrg** [comment]
The fix is live, I seem to get a HSTS response from your domain: https://tls.so/results/saved.indiecertnet.1432868938.4b608f5e88cf0e6f052be9d596cd4cac.html

**Comment by fkooman** [comment]
My site is not the best place to test anymore I guess, because I also fixed the HEAD response :)
