### ISSUE TITLE
Redirects cause header duplication misreporting

### ISSUE THREAD

**Issue by mallegonian** [RaymiiOrg/ssl-decoder#14]
This is a somewhat unusual case, but it had me confused for a while. I've got a default page that's just "301 hell" that was causing the tool to exhibit this issue in an extreme manner.

Observed behavior:
"HSTS header was found multiple times. Only showing the first one"
"HPKP header was found multiple times. Only showing the first one."

Expected behavior: Doesn't follow redirects, doesn't show the above messages.

Example site: https://pluto.sec.gd/ - usually causes a redirect loop, but any redirect may produce this issue.

PHP's get_headers() function seems to dump the headers for every request until it gives up into the response, so even though the server only sends one HSTS and one HPKP header per request, you get 20 or so back.

It looks like you have to use some stream context settings to [disable following redirects](https://php.net/manual/en/function.get-headers.php#95917).

**Comment by RaymiiOrg** [comment]
Thanks for reporting this, and even more thanks for finding the cause. I'd observed it myself but did not look into it that much yet. Fixed and deployed. :+1:

**Comment by mallegonian** [comment]
No problem, thanks for the fix and for the great tool ^.^
