### ISSUE TITLE
PHP warnings in date usage

### ISSUE THREAD

**Issue by vadim6** [RaymiiOrg/ssl-decoder#17]
PHP throws a warning on how date is used in the files, the warning is this:
> PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.

I'm not very good at PHP, but I did some looking around and it seems this code if placed in index.php removes the warning and shows the correct time in the output.
`
date_default_timezone_set('UTC');
`

**Comment by RaymiiOrg** [comment]
Fixed, thanks for reporting!
