### ISSUE TITLE
Update README with required minimum PHP version

### ISSUE THREAD

**Issue by brycied00d** [RaymiiOrg/ssl-decoder#19]
It should be noted in the README that this was written for PHP >= 5.5. Primarily, this is caused by the use of empty() upon a function result which is only supported beginning with PHP 5.5. (http://php.net/manual/en/function.empty.php)
Alternatively, the relevant lines could be changed.

At the risk of scope-creep, two other documentation tweaks:
* `results/` should be chown'd to give the web server permission to write it.
* On Debian systems, the `php-intl` package must be installed to provide/ idn_to_ascii()

**Comment by brycied00d** [comment]
(Okay, I just realised I'd overlooked the entire *Requirements* section)

**Comment by RaymiiOrg** [comment]
Thanks! I host my public facing machine on a CentOS box.
