### ISSUE TITLE
Test for Heartbleed

### ISSUE THREAD

**Issue by JeremyRand** [RaymiiOrg/ssl-decoder#24]
Any chance support could be added for testing a server for vulnerability to Heartbleed?

**Comment by RaymiiOrg** [comment]
If you can provide a reliable command line way (openssl) to test it I could add it,

**Comment by AshleyPoole** [comment]
@RaymiiOrg  Could you use a py script? if so, checkout https://github.com/musalbas/heartbleed-masstest

**Comment by JeremyRand** [comment]
The following 2 SSL scanning tools can detect Heartbleed; I'm not sure if bundling them with ssl-decoder is doable.

https://github.com/rbsec/sslscan
https://github.com/iSECPartners/sslyze

I'm guessing some of their other features would be useful additions as well.

**Comment by RaymiiOrg** [comment]
Fixed in 15e230a85ea76ec7b7c5405ff8cf0953b85503e6.
