### ISSUE TITLE
Not all endpoints are scanned

### ISSUE THREAD

**Issue by AshleyPoole** [RaymiiOrg/ssl-decoder#29]
When a domain name returns multiple endpoints, only one of the endpoints are scanned.

For example, www.ashleypoole.co.uk returns two endpoints which have A records of 104.28.6.2 and 104.28.7.2.
Mxtoolbox link - http://mxtoolbox.com/SuperTool.aspx?action=a%3awww.ashleypoole.co.uk&run=toolpage

When you run the same scan using the SSL Labs API, you receive scan results for both endpoints returned.

Could the SSL Decoder API return results for all endpoints as well?

**Comment by RaymiiOrg** [comment]
I've been working on this for a while but haven't yet found a way I like to fix this. I want to add a URL format $IP:$HOSTNAME so that you can scan any endpoint with a particulair hostname, for example, also to test certain SNI aspects. 

This is coming in a future release, I just don't know when yet.

**Comment by AshleyPoole** [comment]
That would be great. Looking forward to it!

**Comment by AshleyPoole** [comment]
I've just hit this problem again. I scanned a domain twice but each time is scanned a different endpoint (IP).

Rather than trying to limit what endpoints are scanned, could it not be made to scan all endpoints found for a domain name then return a List of say Endpoint objects that contain the current information within Data object?

**Comment by RaymiiOrg** [comment]
Fixed in 988f08b9eb952404b94817a973d1a19ff7c6524b

**Comment by RaymiiOrg** [comment]
See https://tls.so/?host=ashleypoole.co.uk or https://tls.so/?host=raymii.org

**Comment by AshleyPoole** [comment]
Thanks!
