### ISSUE TITLE
CRL parsing not working

### ISSUE THREAD

**Issue by akhepcat** [RaymiiOrg/ssl-decoder#3]
Don't know if this is an issue with self-signed certs or not, but CRL validation on my cert shows an error:  
" - CRL invalid. (https://www.denali.net/ca/crl.pem)"

I've validated that the URL is reachable via the [WebsitePulse test tools](http://www.websitepulse.com/tests/fd5406cd659335bb.html#Web Page/https%3A%2F%2Fwww.denali.net%2Fca%2Fcrl.pem)

 "openssl crl -inform DER -text -in crl.pem" seems to read it just fine. Looks like a logic issue in the code at:  

    if ( strpos($crl_text, "unable to load CRL") === 0 ) {  

Manually testing shows:  

    $ openssl crl -noout -text -inform der -in crl.pem | grep -i unable | wc -c
    0
grabbing tests from further down shows:  

    $ openssl crl -noout -lastupdate -inform der -in  crl.pem 
    lastUpdate=Aug 26 17:57:13 2014 GMT

    $ openssl crl -noout -crlnumber -inform der -in  crl.pem 
    crlNumber=20140408000005

**Comment by RaymiiOrg** [comment]
CRL would not be loaded because the cURL function would try to validate the certificate and fail. Disable validation.
