### ISSUE TITLE
Heartbleed - Everything vulnerable?

### ISSUE THREAD

**Issue by Deehem** [RaymiiOrg/ssl-decoder#30]
Seems the heartbleed test added in e996a42ea0549b415d75bbcc021ab6327cac3cd0 is rendering everything search for as 'vulnerable to heartbleed'.

**Comment by RaymiiOrg** [comment]
Do you have a few examples? I've tested some sites to which the check renders not vulnerable:

- https://tls.so/?host=tweakers.net
- https://tls.so/?host=google.nl
- https://tls.so/?host=pcwebshop.co.uk

And my test machine which has the vulnerable OpenSSL:

- https://tls.so/?host=85.222.224.236

**Comment by Deehem** [comment]
Seems like the results differ between your output and mine:

http://i.dan.xn--3ds443g/1356502015.png

**Comment by Deehem** [comment]
Oops. After looking in to this, the netaddr was missing on this system. Seems to work now.

Possibly better handling of python errors?

**Comment by tomwijnroks** [comment]
I had the same issue on a Debian (wheezy) server. Fixed it by installing the python netaddr module:

`sudo apt-get install python-netaddr`

**Comment by RaymiiOrg** [comment]
Thanks for letting me know about netaddr. Added it to the readme.
