### ISSUE TITLE
Spaces and full stops in field names

### ISSUE THREAD

**Issue by AshleyPoole** [RaymiiOrg/ssl-decoder#33]
In the recent release, For OcspStapling return object, spaces have been added into the field names. This makes it harder when working with the JSON reply.

Example field names: Issuer Name Hash, Next Update, Cert Status.

Also, full stops are also tricky to deal with in the JSON response field names though not as bad as white spaces.

Example field names: tlsv1.2, tlsv1.1.

Before implementing these changes though, it might be better to look at versioning the API on tls.so first though so that these field name changes don't break anything. (https://github.com/RaymiiOrg/ssl-decoder/issues/32)

**Comment by RaymiiOrg** [comment]
I can remove spaces and full stops from the key names, but indeed, after the versioning is done. Out of curiosity, why is this harder to work with?

**Comment by AshleyPoole** [comment]
Background, I'm converting the JSON response to a strongly typed .NET object. I'm then persisting the .NET object to the database as XML so it's query-able.

When I'm converting the JSON to the .NET object, and then from XML to .NET object there's a lot of work dealing with white spaces. Also sometimes the values are set to "not set" rather than null. This makes it extremely hard to code against as normally an API would return the sub object or null if it doesn't exist.

**Comment by AshleyPoole** [comment]
Also, rather than just null, you could even just remove the object altogether from the response if it's not set or null. That's also another standard way of handling it.

**Comment by RaymiiOrg** [comment]
I've fixed the ocsp stapling fields. I'm going to deploy the release next week, if you need to change your code just a heads up.

**Comment by RaymiiOrg** [comment]
If you have any more variables that are not set or contain whitespace, please let me know.

**Comment by AshleyPoole** [comment]
Is the API versioned yet?

Also, do you have an DEV environment or site where the new API could be
tested?

**Comment by RaymiiOrg** [comment]
The API is not versioned yet. There is a dev env here, but I use it as a dev one, so it might be broken from time to time: http://openstack.so/ssl/

**Comment by AshleyPoole** [comment]
OK thanks. Do you have a fixed date yet when this will go live?

Thanks!

**Comment by AshleyPoole** [comment]
@RaymiiOrg full stops / periods are still being used in field names. This still makes it hard for a consumer. Any chance of removing these?
