### ISSUE TITLE
ocsp.startssl.com

### ISSUE THREAD

**Issue by elderone** [RaymiiOrg/ssl-decoder#7]
- http://ocsp.startssl.com/sub/class1/server/ca

Error querying OCSP responder
140480609158824:error:27076072:OCSP routines:PARSE_HTTP_LINE1:server response error:ocsp_ht.c:314:Code=400,Reason=Bad Request

https://forum.startcom.org/viewtopic.php?f=15&t=2661

The OpenSSL command doesn't support HTTP 1.1, but you can try to add the following to your command with newer OpenSSL versions:

-header "HOST" "ocsp.startssl.com"

**Comment by elderone** [comment]
so this script works (after deleting "space" after "\" in third line)
https://gist.github.com/waja/8282171

**Comment by RaymiiOrg** [comment]
Thanks! Fixed now :+1:
