### ISSUE TITLE
TLS 1.3 not recognised

### ISSUE THREAD

**Issue by SharkMachine** [RaymiiOrg/ssl-decoder#73]
![image](https://user-images.githubusercontent.com/7488694/49965737-b1b3f080-ff26-11e8-8b73-7c2e4c420522.png)

Looks like it's enabled (Firefox & Chrome agree as well)... but https://ssldecoder.org does not see it:

![image](https://user-images.githubusercontent.com/7488694/49965454-e70c0e80-ff25-11e8-96d1-019c268aa576.png)

**Comment by RaymiiOrg** [comment]
That is correct. The server where it runs doesn't support it yet.
